# Setting
seed: 1
debug: False
work_dir: ./workdir

dataset: ntu60-transform
dataset_args:
  # Heuristics threshold
  evaluations:
            - CV
            # - CS

  # Flags to select denoising techniques
  transform_flag:
    translation: True
    orient: False
  stat_path: ./data/ntu
  data_path: ./data
  save_path: ./data/ntu_ready