# Setting
gpus: [0]
seed: 1
debug: False
pretrained_path:
work_dir: ./workdir
# Options are: exp or sigmoid
experiment_name: (T1--> 18 Feb)

# Data Loader
dataset: ntu60
dataset_args:
  graph: ntu60
  labeling: intra-inter
  inter_link: pairwise
  hop: 1
  dilation: 2
  # Feeder params
  data_path: ./data/ntu_ready/NTU60_CV_aligned.npz
  window_size: 64
  p_interval:
    - 0.5
    - 1
  p_interval_test:
    - 0.95
  vel: False
  random_rot: True
  sort: False
  # Reduced dataset
  load_part: False
  load_portion: 1.0
  # Batch size
  train_batch_size: 64
  eval_batch_size: 128

# Model
model_type: Trans-GCN
model_args:
  use_att: True
  kernel_size: [3,2]
  dilations: [2,3]
  reduct_ratio: 2
  use_gcn: False
  so2_arg:
    heads: 4
    angle_partitions: 12
    rot_one_axis: False


# Optimizer
# SGD, Adam
optimizer: SGD
optimizer_args:
  SGD:
    lr: 0.05
    momentum: 0.85
    nesterov: True
    weight_decay: 0.0002
  Adam:
    lr: 0.1
    betas: [0.9,0.99]
    weight_decay: 0.0002

# Scheduler
# step, cosine
lr_scheduler: cosine
scheduler_args:
  step:
    max_epoch: 70
    warm_up: 10
    step_lr: [20,50]
  cosine:
    max_epoch: 80
    warm_up: 10